name: website

on: [push]

jobs:
  build_website:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Build website
      run: |
        tox -e website

    - name: Deploy to GitHub pages
      uses: maxheld83/ghpages@v0.1.1
      if: github.ref == 'refs/heads/master'
      env:
        BUILD_DIR: website/html
        GH_PAT: ${{ secrets.GH_PAT }}
